### ISSUE TITLE
SSL Certificate Problem

### ISSUE THREAD

**Issue by hkbertoson** [punctuations/tablespoon#1]
Wanted to try out your tool. Ran ```curl -sSL instl.sh/punctuations/tablespoon/macos | sudo bash ``` and it returns the error of 
```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by punctuations** [comment]
I'll keep this open for now but it is something on the side of [instl.sh](https://instl.sh), for now, the quick fix will just be adding on the `-k` flag onto the command

**Comment by hkbertoson** [comment]
I opened an issue on his Repo regarding the expired certificate. Should be fixed soon hopefully. 

Issue: https://github.com/installer/instl/issues/33

**Comment by punctuations** [comment]
resolved
