### ISSUE TITLE
Sudo is no longer needed in instl.sh command

### ISSUE THREAD

**Issue by MarvinJWendt** [punctuations/tablespoon#17]
Hi @punctuations, I am the creator of instl.sh. I refactored instl, so it doesn't need sudo anymore. The README doesn't include sudo, but the website still has it. Cool project btw!

<img width="580" alt="image" src="https://user-images.githubusercontent.com/31022056/180395811-cad7ff00-b5db-4c76-aae6-f5904a2faac6.png">

**Comment by punctuations** [comment]
Hey, thanks for bringing this to my attention, I just pushed a fix for this on the website
